version: 0.2

phases:
  pre_build:
    commands:
      - cd backend/employee-service
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 806332783810.dkr.ecr.ap-northeast-2.amazonaws.com
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-northeast-2 --name erp-dev
      - REPOSITORY_URI=806332783810.dkr.ecr.ap-northeast-2.amazonaws.com/erp/employee-service
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the JAR file...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Deploying to EKS...
      - kubectl set image deployment/employee-service employee-service=$REPOSITORY_URI:$IMAGE_TAG -n default
      - kubectl rollout status deployment/employee-service -n default
