version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /erp/dev/account-id
    AWS_REGION: /erp/dev/region
    EKS_CLUSTER_NAME: /erp/dev/eks/cluster-name
    ECR_REPOSITORY_PREFIX: /erp/dev/ecr/repository-prefix
    PROJECT_NAME: /erp/dev/project-name
    ENVIRONMENT: /erp/dev/environment

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq
      - kubectl version --client
  
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "Image tag is $IMAGE_TAG"
      - echo "Skipping change detection for first test - will build all services"
      - CHANGED_SERVICES="approval-request-service"
      - LAMBDA_CHANGED="false"
      - HELM_CHANGED="true"
  
  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Building approval-request-service..."
      - cd backend/approval-request-service
      - mvn clean package -DskipTests
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PREFIX/approval-request-service
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - cd ../..
      - echo "Build completed"
  
  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Updating Helm values..."
      - yq eval ".services.approvalRequest.image.tag = \"$IMAGE_TAG\"" -i helm-chart/values-dev.yaml
      - echo "Deploying to EKS with Helm..."
      - helm upgrade erp-microservices ./helm-chart --values ./helm-chart/values-dev.yaml --namespace erp-dev --install --wait --timeout 5m
      - echo "Deployment completed"
      - kubectl get pods -n erp-dev
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - '**/*'
