version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /erp/dev/account-id
    AWS_REGION: /erp/dev/region
    EKS_CLUSTER_NAME: /erp/dev/eks/cluster-name
    ECR_REPOSITORY_PREFIX: /erp/dev/ecr/repository-prefix
    PROJECT_NAME: /erp/dev/project-name
    ENVIRONMENT: /erp/dev/environment

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      # Helm 설치
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version
      
      # yq 설치 (YAML 파싱)
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq
      
      # kubectl 확인
      - kubectl version --client
  
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      
      # ECR 로그인
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      # EKS kubeconfig 업데이트
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      
      # 이미지 태그 생성
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "Image tag: $IMAGE_TAG"
      
      # Git diff로 변경 감지
      - echo "Detecting changed services..."
      - |
        if [ -z "$CODEBUILD_WEBHOOK_PREV_COMMIT" ]; then
          echo "First build or manual trigger, building all services"
          CHANGED_SERVICES="approval-request-service approval-processing-service notification-service"
          LAMBDA_CHANGED="true"
          HELM_CHANGED="true"
        else
          CHANGED_FILES=$(git diff --name-only $CODEBUILD_WEBHOOK_PREV_COMMIT $CODEBUILD_RESOLVED_SOURCE_VERSION)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          CHANGED_SERVICES=""
          LAMBDA_CHANGED="false"
          HELM_CHANGED="false"
          
          # Lambda (Employee Service) 변경 확인
          if echo "$CHANGED_FILES" | grep -q "backend/employee-service/"; then
            LAMBDA_CHANGED="true"
            echo "✓ Lambda (employee-service) changed"
          fi
          
          # EKS 서비스 변경 확인
          if echo "$CHANGED_FILES" | grep -q "backend/approval-request-service/"; then
            CHANGED_SERVICES="$CHANGED_SERVICES approval-request-service"
            echo "✓ approval-request-service changed"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "backend/approval-processing-service/"; then
            CHANGED_SERVICES="$CHANGED_SERVICES approval-processing-service"
            echo "✓ approval-processing-service changed"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "backend/notification-service/"; then
            CHANGED_SERVICES="$CHANGED_SERVICES notification-service"
            echo "✓ notification-service changed"
          fi
          
          # Helm Chart 변경 확인
          if echo "$CHANGED_FILES" | grep -q "helm-chart/"; then
            HELM_CHANGED="true"
            echo "✓ Helm Chart changed, will deploy all EKS services"
            CHANGED_SERVICES="approval-request-service approval-processing-service notification-service"
          fi
        fi
      
      - echo "Services to build: $CHANGED_SERVICES"
      - echo "Lambda changed: $LAMBDA_CHANGED"
      - echo "Helm changed: $HELM_CHANGED"
      - export CHANGED_SERVICES
      - export LAMBDA_CHANGED
      - export HELM_CHANGED
      - export IMAGE_TAG
  
  build:
    commands:
      - echo "Build phase started on $(date)"
      
      # Lambda (Employee Service) 빌드
      - |
        if [ "$LAMBDA_CHANGED" = "true" ]; then
          echo "=========================================="
          echo "Building Lambda: employee-service"
          echo "=========================================="
          cd backend/employee-service
          
          echo "Building JAR..."
          mvn clean package -DskipTests
          
          echo "Building Docker image..."
          LAMBDA_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PREFIX/employee-service-lambda
          docker build -f Dockerfile.lambda -t $LAMBDA_REPO:latest .
          docker tag $LAMBDA_REPO:latest $LAMBDA_REPO:$IMAGE_TAG
          
          echo "Pushing to ECR..."
          docker push $LAMBDA_REPO:latest
          docker push $LAMBDA_REPO:$IMAGE_TAG
          
          echo "Starting ECR image scan..."
          aws ecr start-image-scan \
            --repository-name $ECR_REPOSITORY_PREFIX/employee-service-lambda \
            --image-id imageTag=$IMAGE_TAG \
            --region $AWS_REGION || echo "Scan already in progress"
          
          cd ../..
          echo "✓ Lambda build completed"
        else
          echo "Skipping Lambda build (no changes)"
        fi
      
      # EKS 서비스 빌드
      - |
        if [ -n "$CHANGED_SERVICES" ]; then
          for SERVICE in $CHANGED_SERVICES; do
            echo "=========================================="
            echo "Building EKS service: $SERVICE"
            echo "=========================================="
            cd backend/$SERVICE
            
            echo "Building JAR..."
            mvn clean package -DskipTests
            
            echo "Building Docker image..."
            REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PREFIX/$SERVICE
            docker build -t $REPOSITORY_URI:latest .
            docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
            
            echo "Pushing to ECR..."
            docker push $REPOSITORY_URI:latest
            docker push $REPOSITORY_URI:$IMAGE_TAG
            
            echo "Starting ECR image scan..."
            aws ecr start-image-scan \
              --repository-name $ECR_REPOSITORY_PREFIX/$SERVICE \
              --image-id imageTag=$IMAGE_TAG \
              --region $AWS_REGION || echo "Scan already in progress"
            
            cd ../..
            echo "✓ $SERVICE build completed"
          done
        else
          echo "No EKS services to build"
        fi
  
  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      
      # ECR 스캔 결과 확인 (Lambda)
      - |
        if [ "$LAMBDA_CHANGED" = "true" ]; then
          echo "Waiting for Lambda ECR scan results..."
          for i in {1..30}; do
            SCAN_STATUS=$(aws ecr describe-image-scan-findings \
              --repository-name $ECR_REPOSITORY_PREFIX/employee-service-lambda \
              --image-id imageTag=$IMAGE_TAG \
              --region $AWS_REGION \
              --query 'imageScanStatus.status' \
              --output text 2>/dev/null || echo "IN_PROGRESS")
            
            if [ "$SCAN_STATUS" = "COMPLETE" ]; then
              echo "✓ Lambda scan completed"
              
              CRITICAL_COUNT=$(aws ecr describe-image-scan-findings \
                --repository-name $ECR_REPOSITORY_PREFIX/employee-service-lambda \
                --image-id imageTag=$IMAGE_TAG \
                --region $AWS_REGION \
                --query 'imageScanFindings.findingSeverityCounts.CRITICAL' \
                --output text 2>/dev/null || echo "0")
              
              if [ "$CRITICAL_COUNT" != "None" ] && [ "$CRITICAL_COUNT" != "0" ]; then
                echo "❌ CRITICAL vulnerabilities found in Lambda: $CRITICAL_COUNT"
                echo "Deployment aborted!"
                exit 1
              fi
              
              echo "✓ No critical vulnerabilities in Lambda"
              break
            fi
            
            echo "Scan in progress... ($i/30)"
            sleep 10
          done
          
          # Lambda 함수 업데이트
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name $PROJECT_NAME-$ENVIRONMENT-employee-service \
            --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PREFIX/employee-service-lambda:$IMAGE_TAG \
            --region $AWS_REGION
          
          echo "✓ Lambda function updated"
        fi
      
      # ECR 스캔 결과 확인 (EKS 서비스)
      - |
        if [ -n "$CHANGED_SERVICES" ]; then
          for SERVICE in $CHANGED_SERVICES; do
            echo "Waiting for $SERVICE ECR scan results..."
            for i in {1..30}; do
              SCAN_STATUS=$(aws ecr describe-image-scan-findings \
                --repository-name $ECR_REPOSITORY_PREFIX/$SERVICE \
                --image-id imageTag=$IMAGE_TAG \
                --region $AWS_REGION \
                --query 'imageScanStatus.status' \
                --output text 2>/dev/null || echo "IN_PROGRESS")
              
              if [ "$SCAN_STATUS" = "COMPLETE" ]; then
                echo "✓ $SERVICE scan completed"
                
                CRITICAL_COUNT=$(aws ecr describe-image-scan-findings \
                  --repository-name $ECR_REPOSITORY_PREFIX/$SERVICE \
                  --image-id imageTag=$IMAGE_TAG \
                  --region $AWS_REGION \
                  --query 'imageScanFindings.findingSeverityCounts.CRITICAL' \
                  --output text 2>/dev/null || echo "0")
                
                if [ "$CRITICAL_COUNT" != "None" ] && [ "$CRITICAL_COUNT" != "0" ]; then
                  echo "❌ CRITICAL vulnerabilities found in $SERVICE: $CRITICAL_COUNT"
                  echo "Deployment aborted!"
                  exit 1
                fi
                
                echo "✓ No critical vulnerabilities in $SERVICE"
                break
              fi
              
              echo "Scan in progress... ($i/30)"
              sleep 10
            done
          done
        fi
      
      # Helm Chart values 업데이트
      - |
        if [ -n "$CHANGED_SERVICES" ] || [ "$HELM_CHANGED" = "true" ]; then
          echo "Updating Helm Chart values..."
          
          for SERVICE in $CHANGED_SERVICES; do
            case $SERVICE in
              "approval-request-service")
                SERVICE_KEY="approvalRequest"
                ;;
              "approval-processing-service")
                SERVICE_KEY="approvalProcessing"
                ;;
              "notification-service")
                SERVICE_KEY="notification"
                ;;
            esac
            
            echo "Updating $SERVICE_KEY image tag to $IMAGE_TAG"
            yq eval ".services.$SERVICE_KEY.image.tag = \"$IMAGE_TAG\"" -i helm-chart/values-dev.yaml
          done
          
          echo "✓ Helm values updated"
        fi
      
      # Helm 배포
      - |
        if [ -n "$CHANGED_SERVICES" ] || [ "$HELM_CHANGED" = "true" ]; then
          echo "Deploying to EKS with Helm..."
          helm upgrade erp-dev ./helm-chart \
            --values ./helm-chart/values-dev.yaml \
            --namespace erp-dev \
            --install \
            --wait \
            --timeout 5m
          
          echo "✓ Helm deployment completed"
          
          # 배포 상태 확인
          echo "Checking deployment status..."
          kubectl get pods -n erp-dev
          kubectl get svc -n erp-dev
        else
          echo "No Helm deployment needed"
        fi
      
      - echo "=========================================="
      - echo "Build completed successfully on $(date)"
      - echo "Image tag: $IMAGE_TAG"
      - echo "Services deployed: $CHANGED_SERVICES"
      - echo "Lambda updated: $LAMBDA_CHANGED"
      - echo "=========================================="

artifacts:
  files:
    - '**/*'
