version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /erp/dev/account-id
    AWS_REGION: /erp/dev/region
    EKS_CLUSTER_NAME: /erp/dev/eks/cluster-name
    ECR_REPOSITORY_PREFIX: /erp/dev/ecr/repository-prefix
    PROJECT_NAME: /erp/dev/project-name
    ENVIRONMENT: /erp/dev/environment

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq
      - kubectl version --client
  
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - echo "Detecting changed services..."
      - chmod +x ./scripts/detect-changes.sh
      - ./scripts/detect-changes.sh
  
  build:
    commands:
      - echo "Build phase started on $(date)"
      - chmod +x ./scripts/build-services.sh
      - ./scripts/build-services.sh
  
  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - chmod +x ./scripts/deploy-services.sh
      - ./scripts/deploy-services.sh
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - '**/*'
