apiVersion: v2
name: erp-microservices
description: ERP Microservices Helm Chart with AWS Secrets Manager Integration
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: ERP Team
    email: team@erp.com
