{{- if .Values.awsAuth.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  annotations:
    helm.sh/resource-policy: keep
data:
  mapRoles: |
    - rolearn: {{ .Values.awsAuth.eksNodeRoleArn }}
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{"{{"}}EC2PrivateDNSName{{"}}"}}
    - rolearn: {{ .Values.awsAuth.codebuildRoleArn }}
      groups:
      - system:masters
      username: codebuild
{{- end }}
