apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ .Values.eksNodeRoleArn }}
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{"{{"}}EC2PrivateDNSName{{"}}"}}
    - rolearn: {{ .Values.codebuildRoleArn }}
      groups:
      - system:masters
      username: codebuild
