{{- if .Values.secretsManager.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: rds-secret
    creationPolicy: Owner
  data:
  {{- range .Values.secretsManager.secrets.rds.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.secretsManager.secrets.rds.name }}
      property: {{ . }}
  {{- end }}
{{- end }}
