{{- if .Values.xray.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: xray-daemon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: xray-daemon
  ports:
    - name: xray
      port: 2000
      protocol: UDP
      targetPort: 2000
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xray-daemon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: xray-daemon
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
      serviceAccountName: default
      containers:
      - name: xray-daemon
        image: {{ .Values.xray.image.repository }}:{{ .Values.xray.image.tag }}
        ports:
        - name: xray
          containerPort: 2000
          protocol: UDP
        resources:
          {{- toYaml .Values.xray.resources | nindent 10 }}
{{- end }}
